# Generated by Django 3.2.5 on 2021-07-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EumcDrugData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawdata', models.FileField(upload_to='eumc', verbose_name='약품정보파일')),
                ('location', models.CharField(choices=[('mokdong', '이대목동'), ('seoul', '이대서울')], max_length=50, verbose_name='위치')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '약품마스터파일관리',
                'verbose_name_plural': '약품마스터파일관리',
                'ordering': ('-created',),
            },
        ),
    ]
