# Generated by Django 3.2.5 on 2021-07-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eumc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eumcdrugdata',
            name='rawdata',
            field=models.FileField(upload_to='media/eumc', verbose_name='약품정보파일'),
        ),
    ]
