# Generated by Django 3.2.5 on 2021-07-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eumc', '0002_alter_eumcdrugdata_rawdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eumcdrugdata',
            name='rawdata',
            field=models.FileField(upload_to='eumc', verbose_name='약품정보파일'),
        ),
    ]
